version: '3'
services:
  pwn:
    build: .
    platform: linux/amd64
    restart: always
    ports:
      - 9995:9995
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M