version: '3'
services:
  cervantes:
    build: .
    platform: linux/amd64
    restart: always
    ports:
      - 9992:9992
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
