version: '3'
services:
  autoretrato:
    build: .
    platform: linux/amd64
    restart: always
    ports:
      - 9993:9993
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
